name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - name: Run Release Please
        id: release-please
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # The dart binary from a Flutter SDK facilitates publishing both Flutter and pure-dart packages.
      # https://github.com/dart-lang/setup-dart/blob/2bd11704788983a6a210731656d0042e2df8b2c1/.github/workflows/publish.yml#L39-L41
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.0.2

      - name: Install dependencies
        run: dart pub get

      - name: Publish - dry run
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish --force
